PAYMENT_MODES = [
    {"mode_id": "0", "mode_name": "All Modes"},
    {"mode_id": "1", "mode_name": "Card"},
    {"mode_id": "2", "mode_name": "Cash"},
    {"mode_id": "3", "mode_name": "Points"},
    {"mode_id": "4", "mode_name": "Wallets"},
    {"mode_id": "6", "mode_name": "Brand EMI"},
    {"mode_id": "7", "mode_name": "Sodexo"},
    {"mode_id": "8", "mode_name": "PhonePe"},
    {"mode_id": "9", "mode_name": "UPI PayTm"},
    {"mode_id": "10", "mode_name": "UPI Sale"},
    {"mode_id": "11", "mode_name": "UPI Bharat QR"},
    {"mode_id": "12", "mode_name": "Airtel Bank"},
    {"mode_id": "19", "mode_name": "Paper POS"},
    {"mode_id": "20", "mode_name": "Bank EMI"},
    {"mode_id": "21", "mode_name": "Amazon Pay"},
    {"mode_id": "22", "mode_name": "Sale w/wo Instant Discount"},
    {"mode_id": "23", "mode_name": "Sale Cardless Bank EMI"},
    {"mode_id": "24", "mode_name": "Sale Cardless Brand EMI"},
    {"mode_id": "35", "mode_name": "NBFC Product Sale"},
    {"mode_id": "37", "mode_name": "myEMI"},
    {"mode_id": "39", "mode_name": "Epaylater"},
    {"mode_id": "40", "mode_name": "NTB(New To Business)"},
    {"mode_id": "42", "mode_name": "Zomato Pay"},
    {"mode_id": "44", "mode_name": "STELLR POR"},
    {"mode_id": "45", "mode_name": "STELLR POSA"},
]
