UPI_BANKS = [
    {"bank_code": "1", "upi_bank_name": "HDFC BHARAT QR"},
    {"bank_code": "2", "upi_bank_name": "HDFC UPI"},
    {"bank_code": "3", "upi_bank_name": "AXIS UPI"},
    {"bank_code": "4", "upi_bank_name": "ICICI UPI"},
    {"bank_code": "5", "upi_bank_name": "AXIS BHARAT QR"},
    {"bank_code": "6", "upi_bank_name": "HSBC UPI"},
    {"bank_code": "7", "upi_bank_name": "AMEX BHARAT QR"},
    {"bank_code": "8", "upi_bank_name": "ICICI BHARAT QR"},
    {"bank_code": "9", "upi_bank_name": "IDFC UPI"},
    {"bank_code": "10", "upi_bank_name": "Paytm"},
    {"bank_code": "11", "upi_bank_name": "AIRTEL BANK"},
    {"bank_code": "12", "upi_bank_name": "AIRTEL UPI"},
    {"bank_code": "13", "upi_bank_name": "SBI BHARAT QR"},
    {"bank_code": "14", "upi_bank_name": "INDUSIND BHARAT QR"},
    {"bank_code": "15", "upi_bank_name": "FEDERAL BHARAT QR"},
    {"bank_code": "16", "upi_bank_name": "PayPal QR"},
    {"bank_code": "17", "upi_bank_name": "AmazonPay UPI"},
    {"bank_code": "18", "upi_bank_name": "ATMONEY"},
    {"bank_code": "20", "upi_bank_name": "YES BANK QR"},
    {"bank_code": "21", "upi_bank_name": "twid"},
    {"bank_code": "22", "upi_bank_name": "CITI UPI"},
    {"bank_code": "23", "upi_bank_name": "RBL UPI"},
    {"bank_code": "24", "upi_bank_name": "KOTAK BANK QR"},
    {"bank_code": "25", "upi_bank_name": "SIB UPI BHARAT QR"},
    {"bank_code": "26", "upi_bank_name": "INDIAN BANK UPI BHARAT QR"},
    {"bank_code": "27", "upi_bank_name": "AMAZON SMART STORE"},
    {"bank_code": "28", "upi_bank_name": "CRED pay"},
    {"bank_code": "29", "upi_bank_name": "IDFC FIRST UPI"},
    {"bank_code": "30", "upi_bank_name": "BOB BANK QR"},
    {"bank_code": "31", "upi_bank_name": "Zomato Pay"},
    {"bank_code": "52", "upi_bank_name": "PHONEPE QR"},
]
